server:
  port: 8080
eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8089/eureka
      defaultZone: ${EUREKA_URI:http://localhost:8089/eureka}
  instance:
    #hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: ventas-service
          uri: lb://ventas-service
          predicates:
            - Path=/ventas/**
        - id: socio-service
          uri: lb://socio-service
          predicates:
            - Path=/socio/**
        - id: workers-service
          uri: lb://workers-service
          predicates:
            - Path=/workers/**
        - id: servicios-service
          uri: lb://servicios-service
          predicates:
            - Path=/servicios/**
        - id: prodcat-service
          uri: lb://prodcat-service
          predicates:
            - Path=/categoria/**,/producto/**
